<h1>numpy</h1>

<h2>Creating a numpy array</h2>

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x,id(x),len(x))
type(x)

[1 2 3 4 5] 2088360347728 5


numpy.ndarray

<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

In [2]:
# Conversion of array values

x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n') # prints w/ a carage return

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


<h2>Basic operations</h2>

In [3]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.50000000000001
19.500000000000004
3.8429155598321434


<h2>Multi-dimensional arrays</h2>

In [4]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


<h3>Indexing</h3>

In [5]:
ax[1,3] #indexing

13.0

<h3>Slicing</h3>

In [6]:
ax[1:3,2:4] # [rows, columns] slicing is exclusive, meaning row 3 and column 4 are not included in your output
#ax[:,2:]

array([[12., 13.],
       [22., 23.]])

<h3>Reshaping</h3>


In [ ]:
print(ax.shape)
ax.reshape(9,2)
#ax.reshape(10,3)

<h3>Creating initialized arrays</h3>

In [ ]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)

In [ ]:
ax = np.ones(10)
print(ax)

In [ ]:
ax = np.arange(10)**2
print(ax)

In [ ]:
np.identity(10)

<h3>Matrix multiplication</h3>


In [ ]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

In [ ]:
np.dot(ay,ay.reshape(10,2)) #Dot product

<h3>Comparing numpy arrays with lists</h3>

In [8]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
#print(ax)
#print(ay)
np.dot(ax,ay)

array([[ 15333, 120825],
       [120825, 978405]], dtype=int32)

<h4>Functionalize this</h4>


In [9]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(10)    

datetime.timedelta(0)

<h4>Do the same with python lists</h4>


In [10]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10000)

datetime.timedelta(microseconds=4995)

In [11]:
# Demo of speed: numpy vs. list comprehension - Numpy wins!

for n in [10,100,1000,10000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

10	0:00:00	0:00:00
100	0:00:00	0:00:00
1000	0:00:00	0:00:00.000996
10000	0:00:00	0:00:00.018950


<h3>Selecting elements from an np array</h3>

In [ ]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
np.where(ax%2==0,1,0) # np.where(array nbr is even, if true, replace with 1, else/if false, replace w/ 0) 

# similar to a find/replace in excel

In [ ]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [12]:
import scipy
scipy.nanmean(x)

C:\Users\rjsch\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: scipy.nanmean is deprecated and will be removed in SciPy 2.0.0, use numpy.nanmean instead
  


TypeError: cannot perform reduce with flexible type

<h3>Random number support in numpy</h3>

In [13]:
np.random.normal(size=10)
#np.random.normal(size=(100,100))
#np.random.exponential()
#np.random.exponential(1.0,size=(6,3))
#np.random.randint(-10,10,size=(9,9))

array([-0.40465337, -0.29382323, -0.62884342,  0.89399879, -1.13580063,
        1.26342836,  1.17752847, -0.49967379,  0.37937401, -1.14220743])